# Generated by Django 5.1.5 on 2026-01-24 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeanBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('roast_date', models.DateField(blank=True, null=True)),
                ('roast_level', models.CharField(blank=True, max_length=30)),
                ('tasting_notes', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coffee_dose', models.FloatField(help_text='Amount of coffee in grams')),
                ('water_dose', models.FloatField(help_text='Amount of water in milliliters')),
                ('grind_size_description', models.CharField(blank=True, help_text='Recommended grind size description', max_length=200)),
                ('grind_size_numeric', models.IntegerField(blank=True, help_text='Recommended numeric grind size if applicable', null=True)),
                ('temp', models.FloatField(blank=True, help_text='Brewing temperature', null=True)),
                ('temp_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='F', max_length=1)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brew_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='coffee_tracker.brewmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateTimeField(help_text='Date and time of brewing')),
                ('grind_size_numeric', models.IntegerField(blank=True, help_text='Actual grind size used', null=True)),
                ('water_temp', models.FloatField(blank=True, help_text='Actual water temperature', null=True)),
                ('temp_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='F', max_length=1)),
                ('actual_coffee_dose', models.FloatField(blank=True, help_text='Actual amount of coffee used in grams', null=True)),
                ('actual_water_dose', models.FloatField(blank=True, help_text='Actual amount of water used in milliliters', null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Rating from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('recipe_variations', models.TextField(blank=True, help_text='Notes on any variations from recipe')),
                ('tasting_notes', models.TextField(blank=True)),
                ('grinder_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bean_bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cups', to='coffee_tracker.beanbag')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cups', to='coffee_tracker.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='beanbag',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bean_bags', to='coffee_tracker.roaster'),
        ),
    ]
